/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn4;

import cn4.*;

/**
 *
 * @author Costi
 */
public class CN4UI extends javax.swing.JFrame {

        CN4.FileReadOutput outFirst ;//= CN4.readFromFile("a.txt");
        CN4.FileReadOutput outSecond ;//= CN4.readFromFile("b.txt");
        CN4.FileReadOutput outPutSum ;//= CN4.readFromFile("aplusb.txt");
        CN4.FileReadOutput outputProduct;// = CN4.readFromFile("aorib.txt");
    
    /**
     * Creates new form CN4UI
     */
    public CN4UI() {
        initComponents();
        try
        {
            outFirst = CN4.readFromFile("a.txt");
            outSecond = CN4.readFromFile("b.txt");
            outPutSum = CN4.readFromFile("aplusb.txt");
            outputProduct = CN4.readFromFile("aorib.txt");
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        multBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        processingTV = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkingResultTP = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        epsilonTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        areEqualTF = new javax.swing.JTextField();
        aVectorBtn = new javax.swing.JButton();
        bVectorBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBtn.setText("Add and check");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        multBtn.setText("Multiply and check");
        multBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(processingTV);

        jScrollPane2.setViewportView(checkingResultTP);

        jLabel1.setText("Ar they equal?");

        epsilonTF.setText("1e-5");

        jLabel2.setText("Epsilon:");

        aVectorBtn.setText("A*vector");
        aVectorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aVectorBtnActionPerformed(evt);
            }
        });

        bVectorBtn.setText("B*vector");
        bVectorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVectorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multBtn)
                        .addGap(5, 5, 5)
                        .addComponent(aVectorBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(areEqualTF, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVectorBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(epsilonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(multBtn)
                    .addComponent(epsilonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(aVectorBtn)
                    .addComponent(bVectorBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(areEqualTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        RareMatrix sum = outFirst.A.addWithRareMatrix(outSecond.A);
        this.processingTV.setText(sum.toString());
        this.checkingResultTP.setText(outPutSum.A.toString());
        
        this.areEqualTF.setText(sum.isEqualToMatrixWithEpsilon(outPutSum.A, epsilon()) + "");
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void multBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBtnActionPerformed
        // TODO add your handling code here:
        
        RareMatrix prod = outFirst.A.multiplyWithRareMatrix(outSecond.A);
        this.processingTV.setText(prod.toString());
        this.checkingResultTP.setText(outputProduct.A.toString());
        
        this.areEqualTF.setText("" + prod.isEqualToMatrixWithEpsilon(outputProduct.A, epsilon()));
    }//GEN-LAST:event_multBtnActionPerformed

    private void aVectorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aVectorBtnActionPerformed
        // TODO add your handling code here:
        
        double[] elementsToN = CN4.vectorOfElementsFrom1To(outFirst.A.numOfColumns);
        double[] multiplied = outFirst.A.multiplyWithVector(elementsToN);
        
        this.processingTV.setText(cnjava1.CNJava1.printVector(multiplied));
        this.checkingResultTP.setText(cnjava1.CNJava1.printVector(outFirst.x));
        
        this.areEqualTF.setText("" + CN4.areVectorsEqualWithEpsilon(multiplied, outFirst.x, epsilon()));
        
    }//GEN-LAST:event_aVectorBtnActionPerformed

    private void bVectorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVectorBtnActionPerformed
        // TODO add your handling code here:
        
        double[] elementsToN = CN4.vectorOfElementsFrom1To(outSecond.A.numOfColumns);
        double[] multiplied = outSecond.A.multiplyWithVector(elementsToN);
        
                this.processingTV.setText(cnjava1.CNJava1.printVector(multiplied));
        this.checkingResultTP.setText(cnjava1.CNJava1.printVector(outSecond.x));
        
        this.areEqualTF.setText("" + CN4.areVectorsEqualWithEpsilon(multiplied, outSecond.x, epsilon()));

    }//GEN-LAST:event_bVectorBtnActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CN4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CN4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CN4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CN4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CN4UI().setVisible(true);
            }
        });
    }
    
    private double epsilon()
    {
        return Double.parseDouble(this.epsilonTF.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aVectorBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField areEqualTF;
    private javax.swing.JButton bVectorBtn;
    private javax.swing.JTextPane checkingResultTP;
    private javax.swing.JTextField epsilonTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton multBtn;
    private javax.swing.JTextPane processingTV;
    // End of variables declaration//GEN-END:variables
}
